{% set name = "tigramite" %}
{% set version = "5.2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 376bff91e8461bd082cfb97bd6c635999efc554913afe2470369a2716a344724

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy  >=1.18
    - scipy  >=1.10.0
    - six

test:
  imports:
    - tigramite
    - tigramite.independence_tests
    - tigramite.toymodels
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jakobrunge/tigramite
  summary: 'Tigramite is a python package for causal inference with a focus on time series data'
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: license.txt
  doc_url: https://jakobrunge.github.io/tigramite
  dev_url: https://github.com/jakobrunge/tigramite

extra:
  recipe-maintainers:
    - martinRenou
